[phases.setup]
nixPkgs = ["nodejs", "pnpm", "playwright-driver"]

[phases.build]
dependsOn = ["setup"]
cmds = ["pnpm install && PLAYWRIGHT_BROWSERS_PATH=0 npx playwright install --with-deps chromium && pnpm run build"]

[start]
cmd = "node dist/main.js"

[variables]
PLAYWRIGHT_BROWSERS_PATH = "0"
