[phases.setup]
nixPkgs = ["nodejs", "pnpm", "playwright-driver"]

[phases.build]
dependsOn = ["setup"]
cmds = ["pnpm install && npx playwright install --with-deps chromium && pnpm run build"]

[start]
cmd = "node dist/main.js"
